<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>

        <DebugType>embedded</DebugType>
        <Deterministic>true</Deterministic>
        <RepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</RepoRoot>
        <PathMap>$(RepoRoot)=src/</PathMap>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\libs\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\libs\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>..\libs\BepInEx.dll</HintPath>
      </Reference>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\libs\Newtonsoft.Json.dll</HintPath>
      </Reference>
      <Reference Include="Notiffy">
        <HintPath>..\libs\Notiffy.dll</HintPath>
      </Reference>
      <Reference Include="NukeLib">
        <HintPath>..\libs\NukeLib.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Addressables">
        <HintPath>..\libs\Unity.Addressables.dll</HintPath>
      </Reference>
      <Reference Include="Unity.ResourceManager">
        <HintPath>..\libs\Unity.ResourceManager.dll</HintPath>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>..\libs\Unity.TextMeshPro.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\libs\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>..\libs\UnityEngine.AssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AudioModule">
        <HintPath>..\libs\UnityEngine.AudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\libs\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>..\libs\UnityEngine.InputLegacyModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputModule">
        <HintPath>..\libs\UnityEngine.InputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PhysicsModule">
        <HintPath>..\libs\UnityEngine.PhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\libs\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\libs\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\libs\UnityEngine.UIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestModule">
        <HintPath>..\libs\UnityEngine.UnityWebRequestModule.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
